### ISSUE TITLE
SWComponents won't install (missing files)

### ISSUE THREAD

**Issue by accordd** [dekked/subtitleworkshop#2]
No milestone
No one is assigned

I would like to compile Subtitleworkshop project but the SWComponents miss the following 4 files :

MiMenu.pas
USStringsUtils.pas
USTimeUtils.pas
FastStrings.pas

Can we find these files somewhere?

**Comment by dekked** [comment]
Hey,

Thank you for letting me know of this! Two of the files were there, but two were indeed missing, so I added them.

The files are in the following paths:

Components/Sources/USStringsUtils.pas
Components/Sources/USTimeUtils.pa
Components/Sources/MiMenu.pas
SubtitleAPI/FastStrings.pas
